services:
  - type: web
    name: fidelio-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
